### ISSUE TITLE
Get error when jnitrace an app packed by 360

### ISSUE THREAD

**Issue by syang-ng** [chame1eon/jnitrace#10]
Hello, I test `jnitrace` on an app packed by 360 but got an error message:

command is below:
```shell
jnitrace -l \* my.v1rtyoz.helloworld
```

- Nexus 6P - Android 6.0.1
- frida - 12.8.1
- application: [my.v1rtyoz.helloworld .apk](https://mega.nz/#!ZMMjwKxa!QEWK9WP3f8fahXs06Ibqy6NHf6rjK6fKC1Qp1KJM23gblu)
- displayed error messages
![image](https://user-images.githubusercontent.com/25731241/72400982-c8f68a80-3785-11ea-9cf2-9c257803566e.png)

**Comment by chame1eon** [comment]
Hi, thanks for your bug report. Unfortunately, I have been unable to reproduce the same issue testing on both an AVD and ARM64 based device. Have you tried running it on any other devices? I'll keep having a look, but it is difficult to know if it is fixed if I cannot reproduce.

I have fixed another bug that came up when I was testing with your application, so thanks for that.
