### ISSUE TITLE
 'runtime' is an invalid keyword argument

### ISSUE THREAD

**Issue by jiych** [chame1eon/jnitrace#13]
Hi, when I use `jnitrace`, it told me below errors

frida version:12.2.6
jnitrace version:3.0.7
android version: 4.4.2(kitkat) arm emulator

jnitrace -l xx.so com.xxx
Traceback (most recent call last):
  File "/usr/local/bin/jnitrace", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jnitrace/jnitrace.py", line 552, in main
    script = session.create_script(jscode, runtime="v8")
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 148, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
TypeError: 'runtime' is an invalid keyword argument for this function

**Comment by jiych** [comment]
after some dig, i know this may not jnitrace problem but frida core. But for some reasons I can't use higher frida version, so can we do some remediation in jnitrace as its depence meet?

**Comment by jiych** [comment]
ooooh. doesn't support 12.2.6? frida need >12..

**Comment by chame1eon** [comment]
Hi,

Thanks for letting me know about this. I have pushed a new version that requires Frida 12.5.0 to prevent the error you were getting.

Does Frida 12.5.0 not work for you? What kind of issue are you seeing?

If it does not work I can look at putting a patch in place to support older versions of Frida.

Thanks,

**Comment by oleavr** [comment]
@jiych Frida 12.8.0 should work fine on that emulator. If not, could you tell me if Frida master works for you? I'm about to push a new release and would really like to fix regressions such as this.

**Comment by jiych** [comment]
@oleavr Frida 12.8.20 didn't work for me, I've been opened a new issue here:
https://github.com/frida/frida/issues/1299
I will test Frida master if work on my emulator later.

**Comment by chame1eon** [comment]
Closing as issue filed with the Frida project
