### ISSUE TITLE
`jnitrace -I` syntax error

### ISSUE THREAD

**Issue by eternalsakura** [chame1eon/jnitrace#15]
jnitrace -I work()V -l libmyjni.so com.gdufs.xman
bash: syntax error near unexpected token `('

why?

frida --version
12.8.0

**Comment by chame1eon** [comment]
Hi,

Thanks for submitting the issue.

-l needs to be the name of the library you are hooking, so -l work()V would not work.

You should be able to run the command as:

 jnitrace -l libmyjni.so com.gdufs.xman

Separately, the issue you are seeing is a bash problem as it is trying to interpret the "(" in the command. You can use "\(" to escape the bracket if you run into the problem in the future.

Let me know if that helps.

Thanks

**Comment by eternalsakura** [comment]
-I <string> - is used to specify the exports from a library that should be traced. This is useful for libraries where you only want to trace a small number of methods. The functions jnitrace considers exported are any functions that are directly callable from the Java side, as such, that includes methods bound using RegisterNatives. The option can be supplied multiple times. For example, -I stringFromJNI -I nativeMethod([B)V could be used to include an export from the library called Java_com_nativetest_MainActivity_stringFromJNI and a method bound using RegisterNames with the signature of nativeMethod([B)V.
maybe I means -I <string>

**Comment by eternalsakura** [comment]
```
-I - is used to specify the exports from a library that should be traced. This is useful for libraries where you only want to 
trace a small number of methods. The functions jnitrace considers exported are any functions that are directly callable from the Java side, as such, that includes methods bound using RegisterNatives. The option can be supplied multiple times. For example, -I stringFromJNI -I nativeMethod([B)V could be used to include an export from the library called Java_com_nativetest_MainActivity_stringFromJNI and a method bound using RegisterNames with the signature of nativeMethod([B)V.
```
maybe I means -I String
![image](https://user-images.githubusercontent.com/31586437/86502527-c7be2600-bdd6-11ea-8b1d-b43ee6c4a96c.png)

**Comment by chame1eon** [comment]
Thanks for clarifying, sorry for the initial confusion.

Can you trying modifying your command to one of the following to see if that works?

jnitrace -I "work()V" -l....

jnitrace -l work\(\(V -l...

**Comment by chame1eon** [comment]
Closing this as not heard anything in 2 weeks.
