### ISSUE TITLE
how to use frida to watch va_list

### ISSUE THREAD

**Issue by axhlzy** [chame1eon/jnitrace#19]
JNI函数中会存在变长参数，大概看了一下应该处理为pointer

但是具体怎么处理，取得这里面的值的，还请大佬科普一下  /xk

**Comment by chame1eon** [comment]
Hi,

Thanks for your question. I hope this translates okay. JNI Trace hooks the getMethodID function so it can record how many Java arguments are using in the function. From this it knows how many values to read from the variable-length parameters.

It is all automated so you do not need to worry about it. If you are using the jnitrace-engine plugin in your own project you get the Java arguments in the callback.

Hope that helps.

Thanks

**Comment by chame1eon** [comment]
Closing as over 2 weeks old.
