### ISSUE TITLE
How to install specific version with frida?

### ISSUE THREAD

**Issue by DXCyber409** [chame1eon/jnitrace#21]
For example I'm using frida 12.8.0 family bucket, which version should I get to use?

**Comment by chame1eon** [comment]
Hi,

Thanks for your question. Unfortunately, there is no easy way of running jnitrace with older versions of Frida.

One option is to use a version of jnitrace older than v3.1.0, as those used Frida 12. Other than that you would need to clone the project and modify it to support Frida 12.

Hope that helps. Let me know if you have other questions.

Thanks
