### ISSUE TITLE
filter not work

### ISSUE THREAD

**Issue by RonaldinhoL** [chame1eon/jnitrace#23]
-i Get
-e *
-e .*
--ignore-env
--ignore-vm

i had try many option, but none of them work, it would print evething called

frida-server 14.0.8
android 10, pixel QP1A.191005.007.A3

**Comment by RonaldinhoL** [comment]
另外请问这几个选项的优先级是怎么样的呢？

**Comment by chame1eon** [comment]
Hi, Thanks for filing an issue. Can you let me know what app you were testing on so I can reproduce? On your other question, include takes precedent, so whatever your regex includes will be there, regardless of whether you also exclude something similar.

As a guess, can you try:

 -i Get.*

That might work. All those filters are regex, so when trying to trace methods that begin Get, you must use the regex Get.*

Thanks

**Comment by chame1eon** [comment]
Closing as not heard an update in over a month.
