### ISSUE TITLE
[Not an Issue] Termux Support

### ISSUE THREAD

**Issue by apkunpacker** [chame1eon/jnitrace#28]
Since Frida now can be run in Android Termux fine , please give an -N option to connect to frida-server running on 127.0.0.1 locally, same as 
https://github.com/sensepost/objection 
which have -N option to connect on by default 127.0.0.1:27042 . so if jnitrace have -N it can perfectly run on android standalone , no need of pc as host .
Thanks

**Comment by chame1eon** [comment]
Hi,

Good suggestion. I have added your request to the latest version of jnitrace (version 3.2.0).

The only difference from objection is that the command option is -R rather than -N.

Can you let me know if it works for you?

Thanks

**Comment by apkunpacker** [comment]
i can confirm that it working perfectly on android termux. now no need of pc to run it . awesome work . thanks a lot
